/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsCreateRouteImport } from './routes/sessions.create'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as SessionsCreateIndexRouteImport } from './routes/sessions.create.index'
import { Route as SessionsCreateFormRouteImport } from './routes/sessions.create.form'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsCreateRoute = SessionsCreateRouteImport.update({
  id: '/sessions/create',
  path: '/sessions/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsCreateIndexRoute = SessionsCreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsCreateRoute,
} as any)
const SessionsCreateFormRoute = SessionsCreateFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => SessionsCreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/create': typeof SessionsCreateRouteWithChildren
  '/sessions/create/form': typeof SessionsCreateFormRoute
  '/sessions/create/': typeof SessionsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/create/form': typeof SessionsCreateFormRoute
  '/sessions/create': typeof SessionsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/create': typeof SessionsCreateRouteWithChildren
  '/sessions/create/form': typeof SessionsCreateFormRoute
  '/sessions/create/': typeof SessionsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-profile'
    | '/login'
    | '/signup'
    | '/sessions/$sessionId'
    | '/sessions/create'
    | '/sessions/create/form'
    | '/sessions/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/login'
    | '/signup'
    | '/sessions/$sessionId'
    | '/sessions/create/form'
    | '/sessions/create'
  id:
    | '__root__'
    | '/'
    | '/complete-profile'
    | '/login'
    | '/signup'
    | '/sessions/$sessionId'
    | '/sessions/create'
    | '/sessions/create/form'
    | '/sessions/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsCreateRoute: typeof SessionsCreateRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/create': {
      id: '/sessions/create'
      path: '/sessions/create'
      fullPath: '/sessions/create'
      preLoaderRoute: typeof SessionsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/create/': {
      id: '/sessions/create/'
      path: '/'
      fullPath: '/sessions/create/'
      preLoaderRoute: typeof SessionsCreateIndexRouteImport
      parentRoute: typeof SessionsCreateRoute
    }
    '/sessions/create/form': {
      id: '/sessions/create/form'
      path: '/form'
      fullPath: '/sessions/create/form'
      preLoaderRoute: typeof SessionsCreateFormRouteImport
      parentRoute: typeof SessionsCreateRoute
    }
  }
}

interface SessionsCreateRouteChildren {
  SessionsCreateFormRoute: typeof SessionsCreateFormRoute
  SessionsCreateIndexRoute: typeof SessionsCreateIndexRoute
}

const SessionsCreateRouteChildren: SessionsCreateRouteChildren = {
  SessionsCreateFormRoute: SessionsCreateFormRoute,
  SessionsCreateIndexRoute: SessionsCreateIndexRoute,
}

const SessionsCreateRouteWithChildren = SessionsCreateRoute._addFileChildren(
  SessionsCreateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsCreateRoute: SessionsCreateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
